### ISSUE TITLE
Background Visibility and resolution.

### ISSUE THREAD

**Issue by NS007-dev** [AvidCoder101/Text-Formatter#1]
@AvidCoder101 , the background image is pixelated, and the words are not so readable behind it. Perhaps use a bigger and more simple background?

**Comment by AvidCoder101** [comment]
Ok, thanks.

**Comment by AvidCoder101** [comment]
I've added a new background. Is it better?

**Comment by AvidCoder101** [comment]
I've also removed the unnecessary placeholder in the input. Now all of the text should be visible. Thanks for spotting my styling error.
